### ISSUE TITLE
Have to refresh screen to update information

### ISSUE THREAD

**Issue by eanderson4** [anderson-optimization/frontend-documentation#140]
### Subject of the issue
We cache a lot of information in browser.  When screen is refreshed, the caches are busted leading to slow performance for various parts of the applications.

Here are current reasons the screen needs to be refreshed.

- Map layer stalls, want to refresh a specific map layer
- Assets are added to a project but not displayed on map summary
- Geoanalysis is done on set of assets but the data is not populated in the table

**Comment by eanderson4** [comment]
Added a refresh to arclayers that tries to reload the service.  Let me know if there are issues with it or other layer types that stall.

**Comment by eanderson4** [comment]
4.0-39 should have fixes for all of these

**Comment by jakebanderson321** [comment]
Another example:

When I create a user  and first add them to a team. I have to login to their account. I re-select the team from their user profile and then have to refresh so that the Team dropdown at the top of the application displays team information.

**Comment by jakebanderson321** [comment]
When you rate a parcel, you have to refresh to get the map styling to apply.

**Comment by jakebanderson321** [comment]
Will test the other fixes in 4.0-39 but can't create projects right now due to #149

**Comment by jakebanderson321** [comment]
I'm in 4.47 and buildable acres didn't automatically apply to the parcels in this project. I had to refresh to get the buildable area metric to be available in the configure columns: 

https://v3-dev.andersonopt.com/team/demo-v3/project/-Lb08lxW4pQEPaKTcywK

**Comment by jakebanderson321** [comment]
Other 39 fixes look good

**Comment by jakebanderson321** [comment]
Minimal priority one - when you click "Update Buildable Area" from the composite geometry polygon, the "Buildable Area" value on the parcel detail page doesn't update until after a refresh.
