### ISSUE TITLE
Can't Turn Off Color or Size Column

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#141]
### Subject of the issue
When you graph a run group and apply a color column or size column to a parameter, you can't turn the feature off without a refersh. You can adjust the styling to another parameter, but unchecking the selected parameter has no effect. 

![image](https://user-images.githubusercontent.com/13791320/53761625-9f918080-3e8b-11e9-965c-73ca4a0c4ab0.png)

IRR still selected in the image despite being unchecked. 

### Feature Request
Properly toggle these design features

### Bug Report
Fix bug that maintains run group graph styling when they parameters are unchecked

#### Your environment
Chrome 4.0-39

#### Steps to reproduce
Turn a color column or size column on or off for a run group graph.

#### Expected behaviour
Styling adjusts with toggle

#### Actual behaviour
Style turns on but doesn't turn back off

**Comment by eanderson4** [comment]
Closing this as we are reworking charting system.
