### ISSUE TITLE
Create consistent color palette in web app

### ISSUE THREAD

**Issue by eanderson4** [anderson-optimization/frontend-documentation#143]
### Subject of the issue
There are inconsistencies in styling of the web app, including color palette.  

We will be moving to the attached color palette
![anderson color palette-01](https://user-images.githubusercontent.com/5291870/53836162-7c7ad580-3f4c-11e9-9038-9c08e3159a2b.png)
![anderson color palette-02](https://user-images.githubusercontent.com/5291870/53836163-7c7ad580-3f4c-11e9-9a71-a1ac1eeffa51.png)

**Comment by eanderson4** [comment]
Components that I often use relating to colors

text-warning text-primary ...
tag-outlines
buttons
toaster popups

**Comment by jimmullett** [comment]
- created a _variables.scss file that contains the ao color palette and a map to more generic color variable names using sass variables (ie. $color_primary... and such).  This should serve as our color template to make branding a bit more easy.
- moved src/css/custom.css to src/sass/custom.scss.
- removed unused files from css
- created a custom bootstrap.scss that uses the generic ao color variables
- created a vendor-overrides.scss file that currently contains colors, I thinned it down to make things easier to manager.  The colors here are the generic ao color variables This is for toolkit-light, angular datatable, handsontable, etc.  Should other vendor css overrides be needed, this would be a good place for them
- merged custom.scss and styles.scss into custom.scss, replaced colors with generic ao color variables


- did not convert white or black to color variables
- did not convert all the various grays that were lighter than #e1e1e1 to generic color variables
- did not convert any inline base64 background-image values
- did not convert most of the rgba values
- did not go through and convert colors of any user map config
- did not convert map icons
