### ISSUE TITLE
Add Scale Meter to Google Maps

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#150]
### Subject of the issue
Direct from customer: 

"In Pennsylvania and Maine the State/County GIS systems can be limited in the types of layers that can be added to the maps. Because of this, we are looking to find a way to use Anderson Optimization to provide the underlay pictures for our conceptual designs in AutoCAD. With the wetlands layer open we would be able to do that, however right now the scale existing on the bottom right of the map in Google maps and various GIS systems is not currently available in Anderson Opt. Is there any way we could get this scale added to the Anderson Optimization maps? Let me know if this is a possibility when you get a chance."

<img width="262" alt="Capture" src="https://user-images.githubusercontent.com/13791320/54235673-c9782200-44df-11e9-9f96-406985671f4e.PNG">

### Feature Request
Add Google Maps scale bar to the AO Map

**Comment by jakebanderson321** [comment]
I told the user that this would go into our standard queue amidst other prioritization rather than an immediate implementation since it isn’t a bug.

Could you quote what this would cost to accelerate in case they want to go that route?

**Comment by eanderson4** [comment]
This is coming in -46

**Comment by jakebanderson321** [comment]
Looks good. Any way we can get this to display when users are in full screen mode?

**Comment by eanderson4** [comment]
Yup, this looks like it was a bug, the fullscreen was not accounting for top nav bar.  will be fixed in next release

**Comment by jakebanderson321** [comment]
Great. That sounds good.
