### ISSUE TITLE
Combining parcels into single land asset

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#160]
### Feature Request
Users often work with numerous land parcels. It'd be nice to have a way to aggregate multiple pieces of land into a single land asset - or at least interact with them all at once. 

Then they could have an aggregated buildable area, constraint drawings, etc

If you implement #159, it'd be slick to be able to select numerous assets in the map and have a button in one of the pop-ups to "consolidate parcels." 

They could then do the "Create Asset" flow and copy it to the list like they do from the parcel layer

**Comment by jakebanderson321** [comment]
Pinging - have gotten a handful questions/interest on this feature recently. No need overhaul the pipeline to build it, but it's something our customers and some prospects have expressed interest in.

**Comment by eanderson4** [comment]
Ohio demo has a task that can do this.  reopen if issues
