### ISSUE TITLE
Add pencil/select feature to project list

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#177]
### Subject of the issue
Can we add a pencil select to the project list page similar to the asset list page so that users can delete projects more easily?

Minimal priority - just a nice to have

![image](https://user-images.githubusercontent.com/13791320/55975570-e1ae9e80-5c4f-11e9-85af-aa500b7a5c8f.png)

**Comment by eanderson4** [comment]
This is in 4.5-28
