### ISSUE TITLE
Mass visibility toggle

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#194]
### Subject of the issue
Received questions about the ability to select numerous design elements (parcel boundaries, lines, etc) and toggle the visibility simultaneously rather than one by one. 

Doing one by one is tedious on project page.

Could implement using the ctrl+click multi select or a hide all toggle

**Comment by eanderson4** [comment]
This should be fixed with polygon select and sidebar actions
