### ISSUE TITLE
Parcel layer pop up gets closed out by other layers

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#201]
### Subject of the issue
When a user has the parcel layer on as well as another layer such as the wetland layer, if the user clicks on a parcel that doesn't have a wetland constraint, it displays the "0 results" pop up for the wetlands layer and closes out the parcel layer pop up so that the user can't use the copy feature functionality.

Not a huge issue as people can turn on querying, but this doesn't seem to be widely used, yet.

**Comment by eanderson4** [comment]
Ill look to fix this.

I am not sure ideal behavior but current behavior definitely isnt that nice.  I think it is rare users actually want popups from several layers.  Perhaps when a user toggled on a new layer, it should toggle off queries for all other layers.  They can always toggle back on then.  It may be too non-intuitive though.

**Comment by eanderson4** [comment]
This will be fixed in next release.  I did notice that most likely when you have two arc layers on you will only see one of the results.  I'll have to do some more rework to fix that though.

**Comment by jakebanderson321** [comment]
Sounds good. Yea, not a huge rush but something that I've heard called out or noticed in screen shares with a user or two. They get caught repeatedly clicking and confused

**Comment by eanderson4** [comment]
Closing.  Let me know if more work is needed in this area.
