### ISSUE TITLE
Ratings Not Saving

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#203]
### Subject of the issue
There have been issues from users where parcel ratings that users apply aren't saving. This seems to happen after some parcels have been rated then a new parcel is copied in from the parcel layer. 

I (Jake) am reviewing this further to determine exact replication of bug and will update as I learn more.

**Comment by eanderson4** [comment]
I think I've seen this before but I have a hard time replicating.  It should notify the user if it saves with a pop up. I'll double check to make sure there aren't other cases and maybe add a warning if it doesn't save.

**Comment by jakebanderson321** [comment]
Yeah, i've had a tough time replicating too. Sounds good. I'll keep you posted on what i find.

**Comment by eanderson4** [comment]
If you find an example, please reopen
