### ISSUE TITLE
Full List of Parameters Not in Export Options

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#204]
### Subject of the issue
Users have cited times when items like Project Name & Lat/Lng are not showing up as options within the Exporter feature.

I am investigating further to replicate this behavior.

**Comment by eanderson4** [comment]
Thanks, yah an example will help with the debugging.  

The whole parameter system and columns are in need of an overhaul eventually to get more consistency and remove some bugs like this but for now I'll probably just try and fix any issues that are popping up due to time.

**Comment by jakebanderson321** [comment]
Yep, that seems reasonable. I explained that replicating steps are helpful so if anyone comes across it again, outlining the exact 5-6 steps before hand would be helpful.

**Comment by eanderson4** [comment]
Let me know if you have an example of this.  Closing for now

**Comment by jakebanderson321** [comment]
You fixed this awhile back so all good closing.
