### ISSUE TITLE
Parcel Info columns not Lining Up Properly (Potential ReportAll Issue)

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#205]
### Subject of the issue
Users have cited issues where parcel data is in the wrong column. Specific examples from Penn are cited below. 

Essentially things are shifted one column right. This most often happens with 2 word cites where the 2nd word of the city is in the state column, and everything else also shifts 1 column over. 

![image](https://user-images.githubusercontent.com/13791320/59881410-2011b980-9375-11e9-8ee1-af8504a380d7.png)

**Comment by eanderson4** [comment]
Does this show up in the client or just the csv export?

**Comment by eanderson4** [comment]
Do you have an example I can test

**Comment by jakebanderson321** [comment]
Yes, project example in Slack. 

Happens in both client and export

**Comment by eanderson4** [comment]
This is fixed I believe
