### ISSUE TITLE
Tag Project Creator

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#207]
### Subject of the issue
Create the ability to add the user who created a project as a column in the project list. 

![image](https://user-images.githubusercontent.com/13791320/59884641-8e0eae80-937e-11e9-93f1-adcbe4d874e6.png)

**Comment by eanderson4** [comment]
This is implemented and should be available in 4.6-24 when it goes up

**Comment by jakebanderson321** [comment]
Looks great!
