### ISSUE TITLE
User Polygons Save Underneath Parcel Assets

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#210]
### Subject of the issue
When users draw polygons on a parcel detail page (e.g. for tree cover) or copys a polygon from a layer, the polygon saves underneath the initial parcel polygon.

This makes it so that when a user tries to right click the created polygon to add buffers or styling, it ends up adding it to the initial parcel instead.

### Feature Request
Save copied or drawn polygons above parcel/asset polygons.

**Comment by eanderson4** [comment]
This will be in next release
