### ISSUE TITLE
User Polygons Don't Save Right Away (Ideally fix this with geo analysis release)

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#215]
### Subject of the issue
When users create a manual polygon or polyline, they don't add to the polygon manager right away. They need to make an extra click on the map. 

#### Your environment
~27 and above
Chrome

#### Steps to reproduce
Create user polygon on parcel page.

#### Expected behaviour
Automatically add to the polygon manager.

#### Actual behaviour
User has to switch tools and drag the map around once or twice or click another button to "fire" the user interface to update.

**Comment by eanderson4** [comment]
Is this still a bug?

**Comment by jakebanderson321** [comment]
Nope. This is fixed. Closing.
