### ISSUE TITLE
Buildable Area Polygon from Geo+ Doesn't Work In Composite Geometry

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#218]
### Subject of the issue
When you try to create a composite polygon using the GeoAnalysis+ polygon as the base polygon, the application gives an error.

![image](https://user-images.githubusercontent.com/13791320/61668633-e8af6900-aca2-11e9-946b-55608802d3e8.png)

![image](https://user-images.githubusercontent.com/13791320/61668642-f2d16780-aca2-11e9-98f9-4c367992e6f1.png)

### Feature Request
Make it so that you can exclude user created polygons from Geo+ created buildable area polygons.

#### Your environment
4.6-43

#### Steps to reproduce
Perform geo-analysis + on a parcel
Go into the parcel and create an overlapping polygon
Perform composite geometry attempting to include the buildable area and exclude the user created constraint
Click "Build"

#### Expected behaviour
Creates new "Composite" polygon

#### Actual behaviour
Error message

**Comment by eanderson4** [comment]
I tried fixing what I could until I get to a rewrite of these systems.  This is related to the other geometry issue with multipolygons with holes.

Let me know if you see any issues when testing composite geometry before release

**Comment by jakebanderson321** [comment]
Looks good for the time being!
