### ISSUE TITLE
Maintain Hazard Drawings on Custom Filter

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#220]
### Subject of the issue
When geo-analysis + hazard drawings are displayed, they disappear when a user does a custom filter.

Let's make it so that the hazard drawings persist on the custom filter. 

![image](https://user-images.githubusercontent.com/13791320/62231915-99e08e00-b38a-11e9-8a89-570f9af65190.png)

**Comment by eanderson4** [comment]
This is fixed, i never meant for it to remove drawings on asset changes. 

I've also made it so it should hide hazard drawings if asset is removed and reload them when it is added.
