### ISSUE TITLE
Owner Land Search

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#221]
### Subject of the issue
<Customer>  Used to use a parcel system where they'd click a parcel to get it's owner information.

Then, they could click a button that would provide information for every parcel that the owner owns.

<Customer> would like to replicate this functionality in our system.

### Feature Request
Create the functionality so that a user can select a parcel from our parcel list or map and click a button that would allow them to run a parcel search to pull in other parcels by that land owner.

Ideally, we'd create the behavior that they could pull in every parcel in the project search radius as well as the ability to pull in all of their parcels.

Also, this feature should have the same "Get Count" functionality so that users know how many parcels this would pull in.

Note: This can currently be accomplished by pulling parcels. Copying an owner name and passing that into the owner box on advanced parcel search, and re-running the pull. However, this is a lot of steps. A single click process would be ideal.

**Comment by eanderson4** [comment]
This is implemented, although not yet deployed to all clients.
