### ISSUE TITLE
Uncaught promise exceptions in scenario summary

### ISSUE THREAD

**Issue by jimmullett** [anderson-optimization/frontend-documentation#226]
Scenario AO Site Opt in jim-co on dev generates 3 uncaught promise exceptions coming from get-item.filter, getting these tasks by rn results in a null - looks like getItem filter is used in scenario-summary.

**Comment by eanderson4** [comment]
Scenario system is likely getting an overhaul.  The task management part of this is almost finished and I've started to call it a Module.
