### ISSUE TITLE
Adding First Parcel In Parcel List From Parcel Layer

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#233]
### Subject of the issue
When there are no parcels in a project users have to use multiple steps to add in a parcel from the parcel layer.

### Feature Request
When a user is in a project and there are no parcels in the parcel step, make it so that when a user "Creates Asset" from the parcel layer, it automatically adds to the Parcels step list.

**Comment by eanderson4** [comment]
I think I remember fixing this.  let me know if its still an issue.
