### ISSUE TITLE
Automate Adding a SuperParcel into a Project

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#234]
### Subject of the issue
When a user creates a superparcel, they have to copy asset and paste it into the parcel layer. 

### Feature Request
Make it so that when a user creates a superparcel in a project, it is automatically added to the project

**Comment by eanderson4** [comment]
The machinery for this should be in place.

@jimmullett there is a function attached to the project object that is accessible in the map system called addAsset or something.  It is used to add the assets from creating assets from Parcel layer and any asset that has type `asset:land` from the right click context menu.

**Comment by jakebanderson321** [comment]
The superparcel adds. However, until the user does a refresh, it displays the parcel 3 times in the parcel list:

![image](https://user-images.githubusercontent.com/13791320/68696763-32b6a600-0543-11ea-9df9-ec8032f6a1a3.png)

**Comment by jakebanderson321** [comment]
Also, if the parcel list is already open, the list doesn't update unless the user closes the parcel step and then reopens it or refreshes their browser.

**Comment by jakebanderson321** [comment]
If the user rates the superparcel while there are still 3 instances showing, the rating does not save.

**Comment by jakebanderson321** [comment]
This isn't working. I created a superparcel in this project twice: https://staging.andersonopt.com/team/demo-beta/project/-LtfiQFx1_3wCSDME5Db#project-info

It did not add to the project, so I couldn't test the additional issues mentioned in the comments.

**Comment by eanderson4** [comment]
this seems to work for me

**Comment by jakebanderson321** [comment]
It automatically adds to the map. However, if the parcel list is open, they have to close it and reopen it to update the UI. 

Pretty minimal issue, but would be nice to automatically update the list.

Super in map but not list example, must close list then reopen to display in list:
![image](https://user-images.githubusercontent.com/13791320/70577837-a911ec80-1b71-11ea-9aff-8e01546d7c4b.png)

**Comment by jakebanderson321** [comment]
If you want to close this since the core issue is fixed and then make a Jan issue for automatically updating the list UI that is fine. Feel free to close and create new issue for that in Jan. Up to you.

**Comment by eanderson4** [comment]
alright hsould be fixed on 1.0.17

**Comment by jakebanderson321** [comment]
The UI updates, but it gives this error message, and the parcel no longer remains in the project after a refresh. 

![image](https://user-images.githubusercontent.com/13791320/70585466-f4d09000-1b89-11ea-9b62-f4ef3f0d2558.png)

**Comment by eanderson4** [comment]
alright should be fixed in -19

**Comment by jakebanderson321** [comment]
Looks good
