### ISSUE TITLE
Can't Toggle Off User Uploaded KMZ

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#243]
### Subject of the issue
When a user uploads a KMZ and turns it on from the "User" layer section, it displays.

However, if they uncheck the layer box, the KMZ doesn't disappear from the map

It is necessary to save and refresh to toggle the kmz elements

**Comment by eanderson4** [comment]
This seems to be fixed, reopen if stil an issue.
