### ISSUE TITLE
Other Parcel Layer Asset Creation Issues

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#245]
### Subject of the issue
- When you create asset from parcel layer it shows as invalid date until a refresh 
![image](https://user-images.githubusercontent.com/13791320/64881259-ebce3200-d61f-11e9-813e-e0a331289521.png)

- When you click the parcel marker and rate the parcel, the rating coloring doesn't display until after a refresh

- A customer mentioned they can't view the boundary in the parcel list parcel viewer after copying from parcel layer, but I haven't been able to replicate this
![image](https://user-images.githubusercontent.com/13791320/64882359-90ea0a00-d622-11e9-8862-c676e74bcb60.png)

**Comment by eanderson4** [comment]
This will likely be fixed with new grid.  If not, open new issue for the new grid.
