### ISSUE TITLE
Hide Sidebar Button

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#255]
### Subject of the issue
Users often get overwhelmed by the side bar and forget about the Shift+M hotkey. 

### Feature Request
Create a "Hide" icon to hide the side bar which would in effect mimic the Shift+M hotkey functionality.

This is most pertinent with the layers section of the sidebar since the hotkey is the only way to minimize currently.

**Comment by eanderson4** [comment]
This used to be a function in the old sidebar with buttons.  I'm guessing it will be pretty easy to add.
