### ISSUE TITLE
Rating Styling Requires Refresh

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#257]
### Subject of the issue
If you rate a parcel from the parcel list or map, the project map requires a refresh to display the rating styling. 

### Feature Request
Make the parcel color on the map update when the user applies a rating without having to refresh.

**Comment by eanderson4** [comment]
For me, when rating via the project map, it updates the style.  does that not happen for you?

**Comment by eanderson4** [comment]
I see this is an old issue, I'm guessing your talking about getting it to update when the list is updated

**Comment by jakebanderson321** [comment]
Rating from list now updates color. 

However, there is a map issue. I realized it's not persistent it happens in association with hazard drawings: 

Update rating from map, while hazard drawings are on: parcel color doesn't change, parcel rating on map persists after refresh, doesn't update parcel rating in the list

Update rating from map, hazard drawings on then turned off: same behavior as previous.

Regardless of hazard drawings, updating map on list or map will update color, but the pop up and list do not stay aligned if you make a rating on one then adjust in the other

There may be a couple other quirks, but once these are fixed up, I'll retest. Feel like it might be an underlying issue causing all the various one-offs.

![image](https://user-images.githubusercontent.com/13791320/70577536-0d807c00-1b71-11ea-8741-0166a36cc8f2.png)

**Comment by jakebanderson321** [comment]
Now I get an error and can't update rating from map even before loading hazards. I receive this error v -.17

![image](https://user-images.githubusercontent.com/13791320/70585243-47f61300-1b89-11ea-9b41-2e27605b1bbb.png)

**Comment by eanderson4** [comment]
this appears to be same issue as super parcel.  not sure how the check for distance got reversed all of sudden but that is what caused both these issues

**Comment by jakebanderson321** [comment]
Rating from list updates map immediately. 

Rating from the list and then updating the rating in map doesn't update the rating until after a refresh. 

If a parcel is already rated, rating from the map doesn't work.

**Comment by eanderson4** [comment]
Is this a super common flow?  That someone updates one and then the other.  We are going to be reworking this so the bare minimum that is useable is ideal
