### ISSUE TITLE
Composite Geometry Not Working Properly

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#259]
### Subject of the issue
Composite geometry does not work properly when you use a geoanalysis created polygon that has a hole in it.

The composite polygon fills in the "holes" in the geo analysis buildable area polygon.

Sent an example polygon in slack.

### Feature Request
Properly handle the holes in composite geometry.

**Comment by eanderson4** [comment]
Is this still an issue.  If so, copy the asset to demo-a so Jim can have a look.

**Comment by jakebanderson321** [comment]
Looks good.
