### ISSUE TITLE
UX Improvement: Pop-up overlap

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#263]
### Subject of the issue
Popups and our side bar consistently run into each other. Users often mention this as a pain.

![image](https://user-images.githubusercontent.com/13791320/65922014-8614d080-e3a9-11e9-8c87-26a10589165f.png)

### Feature Request
Make it so that they don't overlap either by displaying the pop up in an open area of the map or by recentering the map so that it doesn't overlap.

**Comment by eanderson4** [comment]
It now pans to the item if there is a popup
