### ISSUE TITLE
Geo analysis error

### ISSUE THREAD

**Issue by jimmullett** [anderson-optimization/frontend-documentation#265]
Received this error when I ran geoanalysis
![image](https://user-images.githubusercontent.com/4043024/66878258-3e2fa500-ef76-11e9-90bd-55849b4fe2ad.png)

- Click “Selectall parcels”
- Click Run task
- Issue replicated on this project: https://dev-build.andersonopt.com/angular-8/team/demo-beta/project/-LogZ_mx4EU301Dou2cF#project-info
- Did not receive issue on production
- Can’t “Show all hazard drawings” created in prod

**Comment by jimmullett** [comment]
@eanderson4 and @jakebanderson321 

I tried to reproduce this one but could not do so in my local dev environment.  That is a different environment than what Jake was using so I went to try to do so in dev-build.andersonopt.com/ag-grid/... (which is my latest). There I was getting CORS errors from ReportAll when trying to add parcels via buffer search.  Are you still seeing this bug?

**Comment by andersonopt** [comment]
This looks like it may be related to adding the config for the file api url
to ao lib and has likely been resolved.

**Comment by andersonopt** [comment]
I can try and look at the report all cors issue tomorrow

**Comment by eanderson4** [comment]
sounds like this got fixed

**Comment by jakebanderson321** [comment]
Looks like this got fix so closing.
