### ISSUE TITLE
Geoanalysis polygons don’t display in polygon manager

### ISSUE THREAD

**Issue by jimmullett** [anderson-optimization/frontend-documentation#271]
Geoanalysis polygons from prod environment don’t display in polygon manager for a parcel
![image](https://user-images.githubusercontent.com/4043024/66896519-33930100-efb2-11e9-806a-0ca4379d94fa.png)

**Comment by jimmullett** [comment]
@jakebanderson321  This looks like the asset view to me, is that correct?

**Comment by jakebanderson321** [comment]
Looks good to me. Yes, that was the asset detail view. However, I am able to see polygons now. Closing for the time being. We can reopen if it crops up again.
