### ISSUE TITLE
Delete asset from project is broken

### ISSUE THREAD

**Issue by jimmullett** [anderson-optimization/frontend-documentation#275]
Delete asset from project (trash icon) button on map doesn’t work and provides this error. It deletes the shape but not the asset and re-appears after a refresh
![image](https://user-images.githubusercontent.com/4043024/66897171-a6e94280-efb3-11e9-8ed5-f14198c75110.png)

**Comment by jakebanderson321** [comment]
This does not appear fixed. 

When I right click and delete via the trash icon, there is no more console error. 

However, the underlying problem persists. 

The delete removes the polygon shape, but it doesn't actually update the project. This is confirmed by the fact that the UI notification doesn't ever say "Project updated" just asset updated. 

It is also shown here, where the blue X icon remains but the polygon shape does not. 

![image](https://user-images.githubusercontent.com/13791320/68141186-aa0c8a00-fef2-11e9-8dff-bbf692ebd56c.png)

After a refresh, the entire asset returns. 

Request: Update the trash icon feature to mimic the function used in the "remove from project" list button.

![image](https://user-images.githubusercontent.com/13791320/68141304-dd4f1900-fef2-11e9-899b-b3ff032edf5e.png)
