### ISSUE TITLE
Flood hazard layer issue

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#282]
### Subject of the issue
Couldn't activate flood hazard layer.

### Bug Report
Console provides this error: 
![image](https://user-images.githubusercontent.com/13791320/68140489-839a1f00-fef1-11e9-9182-d0cfe9d1ac7e.png)

**Comment by jimmullett** [comment]
@jakebanderson321 Could you give me some steps to reproduce on this one?  Thanks!

**Comment by jakebanderson321** [comment]
No problem. However, I just went in to recreate and this is no longer happening.

Not sure why, but it looks like we can forego for now. I'll reopen if it crops up again.

**Comment by jimmullett** [comment]
Ok, sounds good.  Thanks!
