### ISSUE TITLE
"Export KML" feature does not work

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#284]
### Subject of the issue
The "Export KML" feature does not work.

It does not work for the dropdown menu or the traditional "Edit" menu

![image](https://user-images.githubusercontent.com/13791320/68143063-42583e00-fef6-11e9-80ae-a0acb6f805e0.png)
![image](https://user-images.githubusercontent.com/13791320/68143168-81868f00-fef6-11e9-83f9-e9f934e4445d.png)

### Bug Report
Clicking the export button gives the following error: 
![image](https://user-images.githubusercontent.com/13791320/68143087-4dab6980-fef6-11e9-9e16-87e2fc81c5f1.png)

Asset to replicate: https://staging.andersonopt.com/team/demo-beta/asset/team~2Fdemo-beta~2Fasset~2Fra_39069_251300160000_37%252E67

**Comment by eanderson4** [comment]
this looks like it might be a project specific error.  I just tested an export and it seems to work.  looks like it was expecting a wkt string, perhaps it is a wicket object.
