### ISSUE TITLE
Add user to team seems broken

### ISSUE THREAD

**Issue by eanderson4** [anderson-optimization/frontend-documentation#285]
### Subject of the issue
When adding a user to a team using the add user dialog in team config, it gives an error and doesn't add user to the team.

I believe we talked about this and you thought it was a this context thing.

**Comment by eanderson4** [comment]
this is in 1.0.15

**Comment by jakebanderson321** [comment]
Still getting error on ~.15

![image](https://user-images.githubusercontent.com/13791320/70577981-0b6aed00-1b72-11ea-8bd6-ff52138be699.png)

**Comment by jakebanderson321** [comment]
I'm still getting an error message. The user shows up in the team, but then they aren't there after a refresh and the error message still shows.

![image](https://user-images.githubusercontent.com/13791320/70585140-d61dc980-1b88-11ea-9667-1743595328f5.png)

**Comment by jakebanderson321** [comment]
V -.17

**Comment by eanderson4** [comment]
i fixed the team add member thing one more time, it is v .18 now, i added megan back in using the UI

**Comment by jakebanderson321** [comment]
Looks good
