### ISSUE TITLE
Edit Step Feature Doesn't Work Properly

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#290]
### Subject of the issue
Edit Mode in asset categories aren't working properly.

Users are only able to select one asset from the asset list.

I also ran into an instance where clicking anywhere on the row (not just asset name link) would navigate me to the asset and create this error message. however, I haven't been able to replicate the behavior consistently:

It also gives the following error: 
![image](https://user-images.githubusercontent.com/13791320/68696238-33027180-0542-11ea-9272-8925ff4a2d25.png)

**Comment by jimmullett** [comment]
@jakebanderson321 To select more than one asset, ag-grid is expecting a ctrl-click on additional rows.  For part about the error, I did click around to see if I could get it to happen.  No luck yet.  Let's keep this ticket around to see if we can figure out some steps to reproduce.  For now though, maybe take it off the angular-8 board?

**Comment by jakebanderson321** [comment]
Ahhh, that makes sense. Yeah, let's remove from the angular 8 board for now. 

If we're doing a ctrl-click to select numerous rows, is it necessary to have the "Edit Step" button?

**Comment by jakebanderson321** [comment]
Works properly. However, we should provide some user feedback that they need to hold control to select numerous. 

Also, since we don't have the parcel summary anymore, is there a reason we need the edit step button to select rows?

Also, since we don't have the parcel summary view, we should implement some map highlighting when a parcel is selected so that users can tie the list to the map better.
