### ISSUE TITLE
Report Description Not Updating With Layer

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#297]
### Subject of the issue
When the user changes the layer that is active, the report feature is not updating the image title or description

![image](https://user-images.githubusercontent.com/13791320/68700883-51209f80-054b-11ea-9c04-d05488e67e05.png)

**Comment by jimmullett** [comment]
@jakebanderson321 I took a look at this one this eve and I am not sure what I am looking for.  Could you break down the steps to reproduce or expected steps a little bit more for me?  Thanks!

**Comment by jimmullett** [comment]
from Jake via Slack:

When a layer (e.g. wetlands) is turned on, and a user activates the Report feature, the Image Title should auto populate with the name of the layer that is activate e.g. wetlands.  Currently it stays as “Image Title”.

Steps to recreate:
- Turn on layer
- Activate report feature

Expected result: image title = layer name
Actual result: image title = ‘image title’

**Comment by jakebanderson321** [comment]
Looks good.
