### ISSUE TITLE
Modify Selection Box Floats

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#298]
### Subject of the issue
When the sidebar is long enough that the user can scroll, if the user scrolls down and tries to modify their selection the box is pulled away from the "Modify Selection" dropdown so that users can't select clear all. 

![image](https://user-images.githubusercontent.com/13791320/68701221-e885f280-054b-11ea-8372-4f88af3b6515.png)

#### Steps to reproduce
Run super parcel task and then select several assets. This should make the sidebar long enough to scroll down.

**Comment by jimmullett** [comment]
I have the beginnings of a fix for this.  I think it may require a few adjustments down the road.  Specifically if we see the menu items starting to be clipped by the side menu area.  At that point I may need to add a additional cases to the switch that is happening here.

**Comment by jakebanderson321** [comment]
This looks good for now. i think we're going to be doing a pretty significant UI/design update to the app in not too long, so I think this should be sufficient for the time being.
