### ISSUE TITLE
Create Asset From Drawing Not Working

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#299]
### Subject of the issue
If a user draws a polyline in a project and then uses the right-click Create Asset feature, it doesn't work properly.

The asset gets created, but it isn't available in the project. 

This issue does not seem to happen using a polygon drawing to create a land asset.

#### Expected behaviour
Asset is created and is saved into the project

#### Actual behaviour
Asset is created but is not in the project.

**Comment by eanderson4** [comment]
some FYI in case Jim picks this up.

The machinery is there for this.  Currently the project.$addAsset function (I'm guessing project-detail controller) currently is filtering for only types that start with `asset:land`.  we would need to expand this and ensure the assets are added to appropriate step based on asset type.

**Comment by jakebanderson321** [comment]
Looks good.
