### ISSUE TITLE
error taking a report image

### ISSUE THREAD

**Issue by jimmullett** [anderson-optimization/frontend-documentation#309]
@jakebanderson321  entered this bug in slack:

Got this error taking a report image on this parcel: https://staging.andersonopt.com/team/demo-alpha/asset/-LtlRMsI02KzdcIC2lYo?tid=demo-alpha

![image](https://user-images.githubusercontent.com/4043024/69084048-a1db4100-0a00-11ea-8fdf-8791c27ffdc5.png)

I then clicked the screen and it appeared then disappeared
If i click around/move my mouse the image comes up so ultimately works but report feature doesn’t seem to be behaving completely properly.

**Comment by jakebanderson321** [comment]
I'm still getting this error is V1.07

![image](https://user-images.githubusercontent.com/13791320/69381790-2507cb80-0c7b-11ea-98a8-a5207a73c29d.png)

https://staging.andersonopt.com/team/demo-alpha/asset/-LtlRMsI02KzdcIC2lYo?tid=demo-alpha

**Comment by jimmullett** [comment]
This one didn't make it into v1.0.7.  Will be in the next one.
