### ISSUE TITLE
Add back project filter

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#321]
### Subject of the issue
With the old project table, there was a quick search name filter. Can we add that back?

![image](https://user-images.githubusercontent.com/13791320/69380548-47e4b080-0c78-11ea-81cf-ff0c393ae32c.png)

**Comment by jakebanderson321** [comment]
Guess this is reasonably similar to using name table filter so maybe i'll just tell them to do that instead.

**Comment by eanderson4** [comment]
There is also a quick filter that would be more closely related to the functionality this provides

UI wise we would have to find where to put it, perhaps right back where it was before

this is a convenient name filter if you want to do that, not as streamlined as old filter that was filtered as typing.
![image](https://user-images.githubusercontent.com/5291870/69381256-92166380-0c71-11ea-929e-2c61fe0ed23b.png)

**Comment by eanderson4** [comment]
I would propose we add the ag-grid quick filter in similar way to the old magnifying glass next to the name

**Comment by eanderson4** [comment]
https://www.ag-grid.com/javascript-grid-filter-quick/#example-quick-filter
