### ISSUE TITLE
Add "Confirm" prompt to freeform polygon search.

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#328]
### Subject of the issue
There is not a "Confirm" parcel search for our freeform parcel search like there is for our standard parcel search: 

This creates risk or users accidentally triggering a search. E.g. a user accidentally pulled 2K parcels because they didn't have a radius. 

### Feature Request
Add the "Confirm" pop up like below to all other searches like we have it for our standard parcel search:

![image](https://user-images.githubusercontent.com/13791320/69461176-8becb980-0d3b-11ea-80d8-5b753ad17a79.png)

Not necessary in Week 1 patch.

**Comment by eanderson4** [comment]
I toggled enforce dry run which doesn't quite do this but does not allow to run task before running dry run.

**Comment by jakebanderson321** [comment]
Makes sense
