### ISSUE TITLE
Multi-select on map not registering consistently

### ISSUE THREAD

**Issue by megankostanick** [anderson-optimization/frontend-documentation#334]
### Subject of the issue
Not able to consistently use multi-select on the map as expected.

### Bug Report
When I was on the map of a project, I tried to select multiple parcels to combine, but nothing seemed to register.  

#### Your environment
* v1.0.13
* Chrome

#### Steps to reproduce
I tired to do multi-select by using the 'command' key + clicking on the blue x icon of a given parcel. I had already been looking at the project for a while and had been doing other things in the project before I attempted to use multi-select to select parcels. 

After I refreshed the browser, multi-select worked again.

Attached is a screenshot of the developer tool when Jake and I were replicating the issue. We didn't see any obvious errors. 

#### Expected behaviour
I expected that when I hit "command" + clicked on the blue x, it would select that parcel / bring up the parcel information. I would not expect to need to refresh the browser in order to have multi-select register. 

#### Actual behaviour
When I used "command" + clicked the blue x icon, nothing seemed to register in the map interface (e.g. no popup about the parcel/didn't select it). 
![Multi-Select - Developer Tool ](https://user-images.githubusercontent.com/58529297/70174102-870bfc00-1691-11ea-8591-9d632ab8759a.png)

**Comment by megankostanick** [comment]
There seems to be a similar issue sometimes when I click on the blue x icon normally. It doesn't always pop up the normal white details box. It always works with a refresh. Sometimes it seems like it doesn't work when I've clicked other blue x's first -- but it does still work sometimes with that.

**Comment by jakebanderson321** [comment]
related to #336 . Appears to be fixed. will keep eyes open. closing for now.
