### ISSUE TITLE
Ctrl state breaking

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#336]
### Subject of the issue
There are times when users try to click on a layer or asset, and the pop ups don't display properly. They get "selected" as they would with a control+click.

This appears to be an issue with the ctrl state getting messed up. 

This is consistently flagged as a nuisance by users.

### Feature Request
Fix the bug so the ctrl state tracks properly and when a user clicks on an item, the pop-ups display properly.

#### Steps to reproduce
It is tricky to reproduce every time. Here is the easiest way.

Click an item on the map so the pop-up displays properly.
Close the pop up.
Hold the control (command on mac) key on your keyboard
switch screens on your computer
come back to the application and engage with the map
Click on an asset, and the pop up will not display. Instead it will "select"

#### Expected behaviour
Pop up should display when control/command key isn't pressed.

#### Actual behaviour
Item simply gets selected

**Comment by jakebanderson321** [comment]
Aligned to issue #334 . We can close that as well when we close this.

**Comment by jakebanderson321** [comment]
Appears to be good. Hard to be fully sure given sporadic nature. Will keep eyes open while further testing. Closing for now.

**Comment by jakebanderson321** [comment]
Re-opening since I think this is related. 

Now, when a user tries to do a multi-select, they have to release the command key after each click, or else the selected list resets.

Selecting an asset with the control key selected gives the following error: 

![image](https://user-images.githubusercontent.com/13791320/70585561-34977780-1b8a-11ea-98b7-782b96a53af6.png)

**Comment by eanderson4** [comment]
I have lowered the priority of that message.  Ctrl click works for me.  can you explain more whats going on?

**Comment by jakebanderson321** [comment]
When I used to multi select assets, 

I would hold the ctrl/command key and click each asset I wanted to select (without unpressing the control/command key). In other words process was: press & hold control/command key. Click each parcel. 

Now I have to: 

press command/control key and click parcel 1
release command / control key
press command/control key and click parcel 2
release command / control key
etc.

If I hold the command/control key throughout, each time I click a new parcel, it just selects that parcel. In other words, it acts as a standard press.

**Comment by eanderson4** [comment]
yah i get the issue, but its working on my side.  maybe link the project you are working on or something.

**Comment by jakebanderson321** [comment]
Interesting. I tried a couple projects. 

https://staging.andersonopt.com/team/demo-charlie/project/-LYDrEyo5EfBeoLzZIQe#project-info

Maybe it's a mac issue. @megankostanick what happens on your machine?

**Comment by jakebanderson321** [comment]
https://staging.andersonopt.com/team/demo-beta/project/-Lvlt8HKrFUiWoKycAeg#project-info

**Comment by eanderson4** [comment]
those both work on my end, do you have any other errors?

**Comment by eanderson4** [comment]
is that error just popping up once or a bunch of times?

**Comment by jakebanderson321** [comment]
Error only once. 

Maybe not related to the error? 

The list resets every time i click a new parcel but only get the error on the first click if i keep holding. 

If I release each time, then each time i repress+click the error fires again. However, that is when it actually keeps adding to the list

**Comment by eanderson4** [comment]
alright try .20 in a few minutes to see if that resolves it

**Comment by jakebanderson321** [comment]
Looks good.
