### ISSUE TITLE
Parcel Layer Not Displaying Properly

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#341]
### Subject of the issue
When a user turns on the parcel layer, the lines don't display right away. You have to zoom in and out to get them to show up. There is also a no drawing file bug.

![image](https://user-images.githubusercontent.com/13791320/70479502-1dca2580-1aa3-11ea-880a-153b1451fe65.png)

#### Steps to reproduce
Turn on parcel layer.

**Comment by jakebanderson321** [comment]
May be related to #332

**Comment by eanderson4** [comment]
I just looked at this and I'm not able to reproduce.  Is the eye icon blue when the parcel layer is not showing up? 
![image](https://user-images.githubusercontent.com/5291870/70568942-29c2ef80-1b56-11ea-9d80-3b16eb6053d2.png)

**Comment by eanderson4** [comment]
That error is unrelated to his issue

**Comment by jakebanderson321** [comment]
Seems to be behaving. I'll reopen if it crops up. Maybe a one-off layer issue.
