### ISSUE TITLE
Make it easier to expand/collapse green headers on a project (below the map)

### ISSUE THREAD

**Issue by megankostanick** [anderson-optimization/frontend-documentation#344]
### Subject of the issue
It's a little cumbersome to close/expand the green headers on a project below the map (green headers on sections like 'Parcels'). With some small changes, it would be a lot more intuitive for new users.  

### Feature Request
Make the whole area of a green header 'clickable' so that when any part is clicked, it expands or collapses the section. It would also be ideal to add an icon in the header of each green section that indicates that it's expandable (e.g. a carrot icon that changes direction up and down as it's expanded/collapsed). 
![Untitled](https://user-images.githubusercontent.com/58529297/70573214-b5407e80-1b5e-11ea-8ef5-776fd678dfea.png)

#### Your environment
* v1.0.13
* Chrome 

#### Actual behaviour
You can only collapse/expand a section if you click on the white section label

**Comment by eanderson4** [comment]
good idea, just fixed, i'll include in this release about to go out

**Comment by eanderson4** [comment]
this is in 1.0.15

**Comment by jakebanderson321** [comment]
Looks good.
