### ISSUE TITLE
Relabel 'Slope Levels' field to 'Max Slope (%)'

### ISSUE THREAD

**Issue by megankostanick** [anderson-optimization/frontend-documentation#345]
### Feature Request
Give us information on what feature you are looking for.

Relabel 'Slope Levels' (in Geoanalysis) to be a little more specific so the user understands how it's going to be applied. I'd recommend renaming it to 'Max Slope (%)' so they can quickly understand.

![Slope Levels](https://user-images.githubusercontent.com/58529297/70576604-96de8100-1b66-11ea-8ddd-07ebe8cc2c1f.png)

#### Your environment
* v1.0.13
* Chrome

**Comment by eanderson4** [comment]
Definitely happy to change it.  Only thing I would ask, does that make it seem like it would just allow 1 value.  I guess it makes more straightforward and if a user is looking for the more complicated functionality they can figure it out.

**Comment by eanderson4** [comment]
alright should be changed now
